# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_new_weights_cpp <- function(M, LM, t, w, lambda, C_matrix) {
    .Call('_FVDDPpkg_compute_new_weights_cpp', PACKAGE = 'FVDDPpkg', M, LM, t, w, lambda, C_matrix)
}

compute_M_w_cpp <- function(M_past, M_future, n, t_past, t_future, w_past, w_future, atomic, lambda, C_matrix_past, C_matrix_future, theta, theta_P0_ystar, nonatomic_w_matrix) {
    .Call('_FVDDPpkg_compute_M_w_cpp', PACKAGE = 'FVDDPpkg', M_past, M_future, n, t_past, t_future, w_past, w_future, atomic, lambda, C_matrix_past, C_matrix_future, theta, theta_P0_ystar, nonatomic_w_matrix)
}

montecarlo_sample_prop_cpp <- function(M, t, N, w, lambda) {
    .Call('_FVDDPpkg_montecarlo_sample_prop_cpp', PACKAGE = 'FVDDPpkg', M, t, N, w, lambda)
}

montecarlo_sample_smooth_cpp <- function(M_past, M_future, n, t_past, t_future, w_past, w_future, N, atomic, lambda, theta, theta_P0_ystar, nonatomic_w_matrix) {
    .Call('_FVDDPpkg_montecarlo_sample_smooth_cpp', PACKAGE = 'FVDDPpkg', M_past, M_future, n, t_past, t_future, w_past, w_future, N, atomic, lambda, theta, theta_P0_ystar, nonatomic_w_matrix)
}

compute_errors_cpp <- function(M_exact, w_exact, M_approx, w_approx, rm_unmatched) {
    .Call('_FVDDPpkg_compute_errors_cpp', PACKAGE = 'FVDDPpkg', M_exact, w_exact, M_approx, w_approx, rm_unmatched)
}

